### ISSUE TITLE
References within the same content type

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/corresponding_node_references#1]
Is the separate content types described in the readme a requirement? I have a reference field that references its same content type (related content) and I'm having trouble getting it to work -- not sure if it's me or the module just doesn't work within a single content type.

**Comment by laryn** [comment]
Also wondering if I should focus attention on https://www.drupal.org/project/cer instead? (I realize nobody has ported it but it seems like the forward-looking replacement for this module).

**Comment by olafgrabienski** [comment]
@laryn Do you remember testing the module also with *different* content types? I'm asking because I have trouble getting the module to work at all, even with different content types.

**Comment by laryn** [comment]
No I don't recall testing that, sorry.

**Comment by herbdool** [comment]
This works.
