### ISSUE TITLE
Module doesn't work for me

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/corresponding_node_references#2]
Interestingly, *Corresponding Node References* (CNR) doesn't work at all for me. That's quite surprising, so I'm not sure if I really understand *how* it's supposed to work.

**Steps To Reproduce**

1. If possible, prepare a vanilla Backdrop site. (I've used https://backdropcms.org/demo.)
2. Install *References* and CNR.
3. Enable References, Node Reference, and CNR.
4. Create a **Page to Post** reference field (node ref. field on the *Page* content type, pointing to the *Post* content type).
5. Create a **Post to Page** reference field (node ref. field on the *Post* content type, pointing to the *Page* content type).
6. Go to `admin/config/system/corresponding_node_references`, and enable the 'corresponding' functionality for the reference fields created above.
7. Create a Page, and reference it to the Post "My first post!".

**Actual behavior**

The Post isn't updated with a reference to the Page.

**Expected Behavior** (according to README)

The Post will automatically be updated with a reference to the Page.

**Additional information**

I've tested some further actions to trigger an update of the Post in question, without success:

- Saved the Post.
- Updated the Post on `admin/config/system/corresponding_node_references/update`.
  (Also updated all content types on this page.)

**Comment by olafgrabienski** [comment]
Doesn't sound related, but just in case: there's a PHP notice coming from one of the Ref. modules when adding content.

> Undefined property: Node::$original in file_field_update() (line 267 of (...)/core/modules/file/file.field.inc).

**Comment by olafgrabienski** [comment]
One more observation: When I change the reference on the Page from "My first post" to another Post, edit then Post 1 and save it, I see the following notice:

> Reference overloading: Test page 1 would of had 2 references and only 1 reference is permitted. Before adding a reference, you would need to edit Test page 1 to remove an existing reference and resave this node to have make it correspond. Or you could allow this reference instance to have more references, go to the field settings of the instance

I get the same message when I update the Posts on the CNR update page. Does that mean, the module isn't able to remove an existing reference?

**Comment by herbdool** [comment]
I think it has something to do with entity_cache now in core. In my quick test I had to clear caches for the other node ref to show up. Here https://github.com/backdrop-contrib/corresponding_node_references/blob/f018d048d22a839fa8d5722eb3f34882d7764bee/corresponding_node_references.crud.inc#L255 it was previously checking for entity_cache module and now it'll always clear cache for the node.

**Comment by olafgrabienski** [comment]
> In my quick test I had to clear caches for the other node ref to show up.

Thanks for looking into the issue, @herbdool, I think you're right. I've cleared all caches after step 7 (*Create a Page, and reference it to the Post*) on my test page, and then the Post has been updated with a corresponding reference to the Page. Do you have already an idea how to adapt line 255?

**Comment by herbdool** [comment]
I've already made a new release. 😁
